Hannah/python integration
jhuapl-boss/neuroglancer pull request #18
Opened 2021-04-13 15:03 UTC by hannahgooden

Hey folks!

This merge request allows us to use the Neuroglancer python package! It includes:
* A fix for the typo in bundle file name
* A new BossCredentialsProvider object that allows us to access APL internal datasets by searching for an access token in three ways:
  * Exposes a new function `neuroglancer.set_boss_token(token)` to let you set a token manually
  * If this token is not set, it will search your filesystem for an intern config file and grab the token from there
  * If there is no intern config file, it uses the token 'public'
* Add back the python package tests in the build action. I have commented out the one that does not work. Consensus is that we will ask Google about it.

I would like to squash this merge request when we perform the merge. If someone who has admin access to this repo could double check that squash merging is allowed, that would be great.

Here's how to test. The instructions [here](https://github.com/jhuapl-boss/neuroglancer/blob/ndmaster/python/README.md) may also be helpful.
* Pull this branch locally
```
git checkout hannah/python-integration
```
* From the root of the repository, install the locally checked out version of `neuroglancer` to `pip`:
```
python setup.py install
```
* Start the python version of the neuroglancer web instance
```
npm run dev-server-python 
```
* Open a new terminal and start a python interpreter instance (or you can do this in a jupyter notebook). Then, run this small script:
```
import neuroglancer
neuroglancer.set_static_content_source(url="http://127.0.0.1:8080")
viewer = neuroglancer.Viewer()
print(viewer)
```
* A URL should be printed. Visit that URL in a browser to view the neuroglancer instance.
* To test that authentication via token is working, try to access an APL internal dataset. I have been using `boss://https://api.bossdb.io/matelsky2020/tutorial/em`. Please try testing all three types of authentication - manual token, intern config file, and the default public token.

Finally, for other commands you can try in the python interpreter/jupyter notebook, check out [Lindsey's wiki page](https://github.com/aplbrain/wiki/blob/f9421c1021ac9273122295f7878a89adf93091f4/projects/neuroglancer/pythonAPI.md)!

2021-04-13 20:07 UTC, hannahgooden commented
Sandy checked and squash merging is allowed for this repo. Please squash and merge this PR when it is approved!

2021-04-15 16:57 UTC, simpksd1 approved these changes

2021-04-16 16:00 UTC, kitchell requested changes

2021-04-16 16:00 UTC, kitchell commented on python/neuroglancer/boss_credentials.py
> +                            self._credentials = config_parser["Default"]["token"]
we should add the capability to look in ['Volume Service'] if no default

2021-04-16 16:00 UTC, kitchell commented on python/neuroglancer/boss_credentials.py
> +        self._credentials = dict(tokenType=u'Token', accessToken=token)
Might be good to add a comment, or type hinting that token should be a string

2021-04-16 16:00 UTC, kitchell commented on python/neuroglancer/default_credentials_manager.py
> +    boss_credentials_provider.set_token(token)
Might be good to add a note, or type hinting that token should be a string

2021-04-16 16:43 UTC, hannahgooden commented on python/neuroglancer/boss_credentials.py
> +                            self._credentials = config_parser["Default"]["token"]
Fixed, thanks for finding the issue

2021-04-16 16:43 UTC, hannahgooden commented on python/neuroglancer/boss_credentials.py
> +        self._credentials = dict(tokenType=u'Token', accessToken=token)
Added!

2021-04-16 17:37 UTC, kitchell commented on python/neuroglancer/boss_credentials.py
> +                            self._credentials = config_parser["Default"]["token"]
should it be in the except for the first try/except?

2021-04-16 17:44 UTC, kitchell commented on python/neuroglancer/boss_credentials.py
> +                            self._credentials = config_parser["Default"]["token"]
no, never mind, I missed the return in the first try, I think this is fine

2021-04-16 17:46 UTC, kitchell approved these changes

2021-04-16 20:53 UTC, merged